### ISSUE TITLE
Gatling core update to 3.11.X

### ISSUE THREAD

**Issue by HamzahSaleemWork** [galax-io/gatling-kafka-plugin#11]
Hey @jigarkhwar, 

I'm sure this is known about and possibly already on the roadmap - it would be nice to support 3.11.X (at the time of writing -> 3.11.3) of the core Gatling framework. Somewhat annoyingly, there was a specific change introduced in Gatling 3.11.3 that is very useful for a very specific journey I'm trying to performance test. Unfortunately, this journey also requires Kafka load injection and as the two versions are incompatible at the moment, it throws a spanner in the works.

There are some workarounds I can use, however they aren't ideal by any means.

This is specifically referring to the SSE protocol, which was updated to support handling SSE messages in a non-blocking way.

Thank you!

**Comment by jigarkhwar** [comment]
Hello!

updating is blocked by https://github.com/gatling/gatling/issues/4569

I’m waiting for 3.11.4
